### ISSUE TITLE
[Bug]: Astro build fails when integrating Vue.js

### ISSUE THREAD

**Issue by misl-smlz** [lukeshay/astro-aws#121]
### 💻

- [ ] Would you like to work on a fix?

### Problem

Open https://stackblitz.com/edit/github-7psfac?file=astro.config.mjs and run `npm run build`. It fails when the `vue` integration is included.

Running the build with `@astro-aws/adapter` adapter fails:
```
~/projects/github-7psfac 6s
❯ npm run build

> @example/basics@0.0.1 build
> astro build

07:54:47 [WARN] The currently selected adapter `@astro-aws/adapter` is not compatible with the image service "Sharp".
07:54:47 [vite] Re-optimizing dependencies because vite config has changed
07:54:47 [build] output: "server"
07:54:47 [build] directory: /home/projects/github-7psfac/dist/
07:54:47 [build] adapter: @astro-aws/adapter
07:54:47 [build] Collecting build info...
07:54:47 [build] ✓ Completed in 241ms.
07:54:47 [build] Building server entrypoints...
07:54:48 [build] ✓ Completed in 979ms.

 building client (vite) 
07:54:49 [vite] ✓ 8 modules transformed.
07:54:49 [vite] dist/client/_astro/client.wVF2Fm0T.js  60.60 kB │ gzip: 24.22 kB
07:54:49 [vite] ✓ built in 915ms
07:54:49 
 finalizing server assets 

07:54:49 [build] Rearranging server assets...
Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'api' -> object with constructor 'Object'
    |     property 'options' -> object with constructor 'Object'
    |     ...
    |     property 'plugins' -> object with constructor 'Array'
    --- index 32 closes the circle
  Stack trace:
    at JSON.stringify (<anonymous>)
    at Module.runHookBuildDone (file:///home/projects/github-7psfac/node_modules/astro/dist/integrations/index.js:382:58)
    at async AstroBuilder.run (file:///home/projects/github-7psfac/node_modules/astro/dist/core/build/index.js:184:7)
    at async build (file:///home/projects/github-7psfac/node_modules/astro/dist/cli/build/index.js:35:3)
    at async cli (file:///home/projects/github-7psfac/node_modules/astro/dist/cli/index.js:172:5)
```

Running the build with `@astrojs/cloudflare` adapter works like expected:
```
~/projects/github-7psfac 6s
❯ npm run build

> @example/basics@0.0.1 build
> astro build

07:51:58 [WARN] [@astrojs/cloudflare] The current configuration does not support image optimization. To allow your project to build with the original, unoptimized images, the image service has been automatically switched to the 'noop' option. See https://docs.astro.build/en/reference/configuration-reference/#imageservice
07:51:59 [vite] Re-optimizing dependencies because vite config has changed
07:51:59 [build] output: "server"
07:51:59 [build] directory: /home/projects/github-7psfac/dist/
07:51:59 [build] adapter: @astrojs/cloudflare
07:51:59 [build] Collecting build info...
07:51:59 [build] ✓ Completed in 232ms.
07:51:59 [build] Building server entrypoints...
07:51:59 [build] ✓ Completed in 742ms.

 building client (vite) 
07:52:00 [vite] ✓ 8 modules transformed.
07:52:00 [vite] dist/_astro/client.wVF2Fm0T.js  60.60 kB │ gzip: 24.22 kB
07:52:00 [vite] ✓ built in 919ms
07:52:00 
 finalizing server assets 

07:52:00 [build] Rearranging server assets...
07:52:01 [build] Server built in 2.47s
07:52:01 [build] Complete!

```

### Environment

- @astro-aws/adapter: 0.5.0
- astro: 4.2.4
- @astrojs/vue: 4.0.8
- vue: 3.4.15

**Comment by lukeshay** [comment]
Will do

**Comment by lukeshay** [comment]
@misl-smlz A new version has been published
