### ISSUE TITLE
[Bug]: createRequire is getting defined twice

### ISSUE THREAD

**Issue by ShivamJoker** [lukeshay/astro-aws#35]
### 💻

- [X] Would you like to work on a fix?

### Input code

```js
import { createRequire } from 'module';
const require = createRequire(import.meta.url);
```

### Current and expected behavior

For some reason require is getting declared like this and lambda throws an error with 

```json
2023-01-03T19:29:05.509Z	undefined	ERROR	Uncaught Exception 	
{
    "errorType": "Runtime.UserCodeSyntaxError",
    "errorMessage": "SyntaxError: Identifier 'createRequire' has already been declared",
    "stack": [
        "Runtime.UserCodeSyntaxError: SyntaxError: Identifier 'createRequire' has already been declared",
        "    at _loadUserApp (file:///var/runtime/index.mjs:997:17)",
        "    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1035:21)",
        "    at async start (file:///var/runtime/index.mjs:1200:23)",
        "    at async file:///var/runtime/index.mjs:1206:1"
    ]
}
```

### Environment

```json
    "@astro-aws/adapter": "^0.2.0",
    "@astrojs/image": "^0.12.1",
    "@astrojs/mdx": "^0.14.0",
    "@astrojs/sitemap": "^1.0.0",
    "@astrojs/tailwind": "^2.1.3",
    "astro": "^1.8.0",
```

### Additional context

I will be happy to add you to my repository if that helps debug the issue.

**Comment by lukeshay** [comment]
Could you add me to the repo so I can see what your source code looks like?
